### ISSUE TITLE
Non Cuda version

### ISSUE THREAD

**Issue by asifali1234** [justanhduc/Phase-based-Frame-Interpolation#1]
Can you please provide a code which supports a cpu without cuda.

**Comment by justanhduc** [comment]
Sure. Originally I intended to make it work for both CPU and GPU but apparently I forgot to do that. I will notify you after I add CPU support.

**Comment by abhijithasokan** [comment]
I also tried to change cupy to numpy by making every cp and xp element as np. But i got this error.

AttributeError: SCFpyr instance has no attribute 'bandIndex'

I didnt find a method to solve this.

**Comment by justanhduc** [comment]
I will pull a new version asap. For your new error, did you use my [pyrTools version](https://github.com/justanhduc/pyPyrTools/tree/test-branch)? The original pyrTools won't work since I have modified a lot. Anyway you still need Cupy so please wait for the new version.

**Comment by justanhduc** [comment]
I uploaded the new version. Please check it out and let me know if there's any problem.

**Comment by asifali1234** [comment]
Thank You. It is working perfectly.
