### ISSUE TITLE
AttributeError: SCFpyr instance has no attribute 'bandIndex'

### ISSUE THREAD

**Issue by abhijithasokan** [justanhduc/Phase-based-Frame-Interpolation#2]
I found no attribute named bandIndex 

index_lo = pyramid.bandIndex(level + 1, band)
index_hi = pyramid.bandIndex(level, band)
index_lo = pyramid.bandIndex(level, band)

Thanks in Advance

**Comment by justanhduc** [comment]
I think you used the original version. Please try my pyrTools version [here](https://github.com/justanhduc/pyPyrTools/tree/test-branch). FYI, I will pull a new version of the codes asap for seaming GPU and CPU usages.

**Comment by justanhduc** [comment]
I uploaded the new version. Please check it out and let me know if there's any problem

**Comment by abhijithasokan** [comment]
Thank you! It works fine now! :yum:
