### ISSUE TITLE
SCFpyr error : No attribute 'xp'

### ISSUE THREAD

**Issue by adrienpitz** [justanhduc/Phase-based-Frame-Interpolation#3]
Got this error when I execute `demo.py`

I installed all the packages needed to make the project run

`Traceback (most recent call last):
  File "demo.py", line 40, in <module>
    new_frames = interpolate_frame(img1, img2, n_frames=args.n_frames, scale=.5**.25, xp=xp)
  File "/home/adrien/Bureau/Phase-based-Frame-Interpolation/frame_interp.py", line 149, in interpolate_frame
    phase_diff = compute_phase_difference(L, R, scale, limit)
  File "/home/adrien/Bureau/Phase-based-Frame-Interpolation/frame_interp.py", line 21, in compute_phase_difference
    xp = L['pyramids'][0].xp
AttributeError: SCFpyr instance has no attribute 'xp'
`

Can anyone help me ?

**Comment by justanhduc** [comment]
@adrienpitz To use GPU I had to tweak the pyramid lib a little bit. You can check the first link in the requirements section or [this](https://github.com/justanhduc/pyPyrTools/tree/test-branch).  Thanks for your interest.

**Comment by adrienpitz** [comment]
Hey @justanhduc ! Thanks for the reply
Actually I used the CPU version so I don't know how to make it work

**Comment by justanhduc** [comment]
@adrienpitz I am not sure what problem you are having now. if the problem is SCFpyr error : No attribute 'xp', then you can download the pyramid lib from the link i provided above (even if you want to use CPU). if you want to know how you can use CPU, you can follow [this ](https://github.com/justanhduc/Phase-based-Frame-Interpolation#usages ). Or you can check the closed issues to see if they are helpful.

**Comment by leemengxing** [comment]
hi, i also meet this error, how to deal with it? thks very much @adrienpitz

**Comment by justanhduc** [comment]
Hi @leemengxing. you should use the `pyPyrTools` from [here](https://github.com/justanhduc/pyPyrTools/tree/test-branch). `xp` was a hack to alternate between CPU and GPU backends (which are NumPy and CuPy, respectively).

**Comment by leemengxing** [comment]
Thanks for the reply, as you mean I should not use pip install pyPyrTools, just git clone for the pyPyrTools link you provided .  Is this correct? thks a lot @justanhduc

**Comment by justanhduc** [comment]
@leemengxing right. If you have any problem, plz let me know.

**Comment by leemengxing** [comment]
i got it. thanks, this will happen "wrapConv.so: invalid ELF header" other error. but others issuse can slove it. now it works well, thks for your works and reply.
